### ISSUE TITLE
ParsEval: extract unique ref/pred features, perfect matches, ...

### ISSUE THREAD

**Issue by satta** [BrendelGroup/AEGeAn#135]
Hi,

is there any way to pull out only those features which are unique to the reference or prediction? Or those being perfect/non-perfect matches? This would be great to figure out what types/families of genes an annotation pipeline is struggling with, and to get an idea of what could be improved.
I could not find a parameter to `parseval` to do any of these -- is there a postprocessing script that you use? Otherwise, consider this a feature request ;)

Cheers
S.

**Comment by standage** [comment]
Excellent question.

Regarding the first question, you can use `parseval -k` to create a filter file which allows you to specify the min/max number of gene models per locus. If you wanted to get, for instance, loci with a single reference gene models and no prediction gene models, you would use the following filters.

```
GeneCount        =       1         R
GeneCount        =       0         P
```

The filter file has a description of all the available filters and how to set them. Also, make sure to include the `-a` option unless you have run `make install`.

**Note**: this will be a pretty boring file as far as comparison statistics are concerned: no comparisons will be performed! But it should be pretty easy to pull out IDs of genes unique to the reference or the prediction.

-----

Regarding the second question, I have *kind of* implemented this, but only for the HTML output mode. I implemented it separate of filtering, so essentially I just created additional pages with links to loci containing comparisons that fit each category: a "perfect matches" page with links to loci containing at least 1 perfect match between reference and prediction, a "CDS matches" page, and so on. These are in the root of the HTML output directory.

Take a look at these and let me know what you think. The HTML output mode is definitely not as convenient for parsing with scripts, but it is pretty nice for exploratory data analysis.

**Comment by satta** [comment]
Ah, I didn't know about `parseval -k`. Useful. 
Will also try the HTML output. I was already suspecting this functionality was hiding somewhere I just didn't find it... ;)

**Comment by standage** [comment]
The ParsEval `-p` flag is useful with `-f html`. Maybe I should turn it on by default...

**Comment by standage** [comment]
I thought this was all pretty clear from the usage statement. But clear to me (the primary developer) doesn't always mean clear to users or other developers. Please do let me know there is anything I can do to improve the usage statement and/or documentation.

**Comment by standage** [comment]
Closing this issue. Feel free to follow up if you have any additional questions.

**Comment by satta** [comment]
Hmmm. I just tried this with the filter file above and while I expect some results because:
```
  Gene loci................................5376
    shared.................................5105
    unique to reference....................162
    unique to prediction...................109
```

I get no results after filtering:

```
$ ~/AEGeAn/bin/parseval -r ~/AEGeAn/pe.filter -a ~/AEGeAn/data/share/  ../../../GFF/results/Pfalciparum.noseq.gff3.gz pseudo.out.gff3
[...]
============================================================
========== ParsEval Summary
============================================================

Started:                04 Aug 2015, 03:58PM
Reference annotations:  ../../../GFF/results/Pfalciparum.noseq.gff3.gz
Prediction annotations: pseudo.out.gff3
Executing command:      /nfs/users/nfs_s/ss34/AEGeAn/bin/parseval -r /nfs/users/nfs_s/ss34/AEGeAn/pe.filter -a ./data/share/ ../../../GFF/results/Pfalciparum.noseq.gff3.gz pseudo.out.gff3

No loci for comparison
```
Did I do something wrong? Where is the output sent exactly?

**Comment by standage** [comment]
Sorry for the delayed response.

Are you saying you used the example from my May 29th comment on the thread? If so, did you see the note? No comparisons are performed if you're only looking at genes from one source.

**Comment by satta** [comment]
Yes, I did use that example. Hmm. But how do I find out which genes _are_ only in the reference or the prediction then? I don't get any output other than what I showed you above (apart from a few complaints about missing mRNAs in non-coding genes)...

**Comment by satta** [comment]
I'd like to get this back to your attention please... I have a feeling there has been a misunderstanding of what I am trying to do?

**Comment by standage** [comment]
Sorry that I've let this slip through the cracks. My attention has been elsewhere, and when it's weeks between times that I look at this thread, some of the details were fuzzy.

So the issue is that when the filter is used as described above, no comparisons are actually performed, and so no output is produced. This is a valid use case where we would want some output, even though no comparison statistics are reported.

If you find a different solution in the mean time, that's great. But I do plan on addressing this issue, even if I can't make any promises as to when I'll get to it.

**Comment by satta** [comment]
No worries. I can imagine the question of uncompared reference-only or prediction-only genes to be interesting to other users as well, especially if they are using ParsEval to test and benchmark their gene finders (to find out what kind of gene they are typically missing or overpredicting.
I think I can work with my solution for now, but I'm looking forward for any proper implementation ;)
Thanks again!

**Comment by standage** [comment]
It turns out a stupid copy/paste error was responsible--at least in part--for the incorrect behavior we saw before. Please let me know whether the latest master fixes this for you.

**Comment by satta** [comment]
Nice, thanks for checking! Will try it when I find some time.

**Comment by satta** [comment]
Excellent, that fixed the problem. Now I get some output for my filter command.
