### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lfaino** [BrendelGroup/AEGeAn#179]
Dear Developers,
I'm using the tool AEGeAn but for one GFF file i get this error: 

```
Assertion failed: (agn_typecheck_gene(fn)), function gene_stream_next, file src/core/AgnGeneStream.c, line 255
```

can you please help?
I'm summarizing some results and only one GFF file out of 21 does not work.

thanks
Luigi

**Comment by standage** [comment]
Thanks for the report Luigi!

I'll be happy to take a look at this for you, but it's hard to troubleshoot without more information. Is there any way you could post the problematic GFF3 file? Or a subset of the file that replicates the issue?

Also, it would be helpful to know the following.

- What operating system (distribution and version) are you running?
- What version of AEGeAn do you have installed?
- What is the precise command you're running?

Thanks!
Daniel

**Comment by lfaino** [comment]
Thanks for the help; here the info that you asked.

The version should be the latest one. I downloaded yesterday.

Name of the system:
Linux pathos 4.4.0-26-generic #45-Ubuntu SMP Mon Jun 20 17:28:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

This is the command but for the other 19, it works:
parseval -g -o file -s -w 

here the reference that works with all the other comparisons: 
[VDAG_Jr2_v4.0.NCBIorder.newGeneIds.manualAnnotation.removeNonCAnonical.gff3.zip](https://github.com/BrendelGroup/AEGeAn/files/493653/VDAG_Jr2_v4.0.NCBIorder.newGeneIds.manualAnnotation.removeNonCAnonical.gff3.zip)

This is the file that gives error; the only one:
[finalAnnotation.gff3.zip](https://github.com/BrendelGroup/AEGeAn/files/493651/finalAnnotation.gff3.zip)

**Comment by standage** [comment]
Thanks for sharing Luigi.

It looks like you have several gene features that have exact duplicates in the GFF3 file. The following command shows 8 of them that appear twice.

```
sort finalAnnotation.gff3 | uniq -c | sort -rn | head
```

I was hoping that getting rid of these duplicates would be sufficient.

```
sort finalAnnotation.gff3 | uniq | gt gff3 -sort -tidy -file -o final-clean.gff3
```

But I got the assertion error again when running ParsEval.

```
parseval -s VDAG_Jr2_v4.0.NCBIorder.newGeneIds.manualAnnotation.removeNonCAnonical.gff3 final-clean.gff3
```

It turns out there are some non-exact duplicates as well, which are easier to see after running `gt gff3 -sort -tidy`.

```
###
Chr4    .       gene    1882906 1886098 .       -       .       ID=gene8429;Name=EVM%20prediction%20Chr4.567
Chr4    .       mRNA    1882906 1886098 .       -       .       ID=mRNA8432;Parent=gene8429
Chr4    .       exon    1882906 1885657 .       -       .       Parent=mRNA8432
Chr4    .       CDS     1883533 1885657 .       -       1       Parent=mRNA8432
Chr4    .       CDS     1885721 1885860 .       -       0       Parent=mRNA8432
Chr4    .       exon    1885721 1886098 .       -       .       Parent=mRNA8432
Chr4    .       mRNA    1882906 1887122 .       -       .       ID=mRNA8433;Parent=gene8429
Chr4    .       exon    1882906 1885657 .       -       .       Parent=mRNA8433
Chr4    .       CDS     1883533 1885657 .       -       1       Parent=mRNA8433
Chr4    .       CDS     1885721 1885806 .       -       0       Parent=mRNA8433
Chr4    .       exon    1885721 1885841 .       -       .       Parent=mRNA8433
Chr4    .       exon    1886173 1887122 .       -       .       Parent=mRNA8433
Chr4    .       gene    1882906 1887122 .       -       .       ID=gene8429;Name=EVM%20prediction%20Chr4.567
###

You see, there are two gene features with the same ID and start position but a different stop position. I'm not sure what went wrong, but this is definitely an issue with the data file.
```

**Comment by standage** [comment]
Ahh, it looks like the second (unnecessary) gene feature corresponds to the second annotated isoform (mRNA feature). It looks like a script or a program went wrong somewhere.

**Comment by standage** [comment]
Looking back at the original (unsorted) GFF3, the intent seems a bit more clear.

```
Chr4    .       gene    1882906 1886098 .       -       .       ID=evm.TU.Chr4.567;Name=EVM%20prediction%20Chr4.567
Chr4    .       mRNA    1882906 1886098 .       -       .       ID=evm.model.Chr4.567;Parent=evm.TU.Chr4.567
Chr4    .       exon    1882906 1885657 .       -       .       Parent=evm.model.Chr4.567
Chr4    .       exon    1885721 1886098 .       -       .       Parent=evm.model.Chr4.567
Chr4    .       CDS     1883533 1885657 .       -       1       Parent=evm.model.Chr4.567
Chr4    .       CDS     1885721 1885860 .       -       0       Parent=evm.model.Chr4.567
Chr4    .       gene    1882906 1887122 .       -       .       ID=evm.TU.Chr4.567;Name=EVM%20prediction%20Chr4.567
Chr4    .       mRNA    1882906 1887122 .       -       .       ID=evm.model.Chr4.567.1.57783c1b;Parent=evm.TU.Chr4.567
Chr4    .       exon    1882906 1885657 .       -       .       Parent=evm.model.Chr4.567.1.57783c1b
Chr4    .       exon    1885721 1885841 .       -       .       Parent=evm.model.Chr4.567.1.57783c1b
Chr4    .       exon    1886173 1887122 .       -       .       Parent=evm.model.Chr4.567.1.57783c1b
Chr4    .       CDS     1883533 1885657 .       -       1       Parent=evm.model.Chr4.567.1.57783c1b
Chr4    .       CDS     1885721 1885806 .       -       0       Parent=evm.model.Chr4.567.1.57783c1b
```

The person/script/program that created this GFF3 file must have assumed that each mRNA feature must have its own gene feature. When annotating alternatively spliced isoforms, you are not supposed to declare a gene feature for each mRNA. There should be only one gene feature that spans all mRNAs associated with the gene. Examples from the [GFF3 specification](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) are pretty clear on this.

I hope this helps!

**Comment by lfaino** [comment]
Hi Daniel,
I correct my prediction software and now should be better. However, I have
a question that is not issue related. can I ask here?

Luigi



2016-09-26 19:57 GMT+02:00 Daniel Standage <notifications@github.com>:

**Comment by standage** [comment]
Hi Luigi,

Glad to hear it! You're welcome to ask related questions here, although if they're unrelated to this issue it's preferred that you open a new issue thread.

And if you feel satisfied with this issue, feel free to close it as resolved.

Best,
Daniel
