### ISSUE TITLE
gaeval bug

### ISSUE THREAD

**Issue by gongyh** [BrendelGroup/AEGeAn#181]
Assertion failed: (strcmp(id, fid) == 0), function agn_typecheck_feature_combined_length, file src/core/AgnTypecheck.c, line 60.
This is a bug, please report it at https://github.com/standage/AEGeAn/issues.

**Comment by standage** [comment]
Can you provide any more context for this error message? There is very little we can do to help otherwise.

**Comment by standage** [comment]
Feel free to re-open this thread if you still need help and can provide additional details.
