### ISSUE TITLE
not able to decompress source code

### ISSUE THREAD

**Issue by teshu02** [BrendelGroup/AEGeAn#189]
curl https://github.com/standage/AEGeAn/archive/v0.15.0.tar.gz > AEGeAn-0.15.1.tar.gz
$> tar xzf AEGeAn-0.15.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by teshu02** [comment]
@standage Thanks

**Comment by standage** [comment]
I will close this thread for now. Feel free to re-open it if you continue to have problems downloading, or to open a new one if you get stuck with a different problem. Good luck!
