### ISSUE TITLE
Running into an error

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BrendelGroup/AEGeAn#190]
Hello, 

I am using Parseval to compare two gene models for the same species. I keep running into the following error.

Assertion failed: (agn_typecheck_gene(fn)), function gene_stream_next, file src/core/AgnGeneStream.c, line 225.
This is a bug, please report it at https://github.com/standage/AEGeAn/issues.

Please help.

Thank you.

**Comment by standage** [comment]
Greetings @sagnikbanerjee15, and thanks for your report.

ParsEval's GFF3 input files must adhere to some formatting conventions, see http://aegean.readthedocs.io/en/stable/parseval.html for more info.

If this doesn't fix things for you, please post your input files (or a large enough subset thereof that will trigger the same error message). Cheers!

**Comment by sagnikbanerjee15** [comment]
Hello Daniel,

Thank you for your reply. I did run gff3validator on my gff3 files. There were no warnings or error for one of the files. For the other files there were some error but in the end it printed a message of acceptance. 

Thank you.

**Comment by standage** [comment]
A valid GFF3 file is not necessarily suitable input for ParsEval. Please check whether the GFF3 files satisfy the additional requirements stipulated in the link I provided above.

**Comment by sagnikbanerjee15** [comment]
Thank you. I will look into the gff3 file.

**Comment by standage** [comment]
Migrated from #192, @sagnikbanerjee15 said:

----------

Hello,

I split my gff3 by chromosomes since the last time I tried to run them all together I encountered an error. The runs were completed without any error for most of the chromosomes. In one of the cases I got a segmentation fault. I have attached the reference and the predicted files.

This is the command I used.

```
chromosome=6
nohup parseval -w -x AGPv4 -y AGPv3 -f html -o AGPv4_to_AGPv3_parseval.${chromosome} Zea_mays.AGPv4.39.tidy.${chromosome}.gff3 Gene_Models_v3_to_v4.sorted.no.chr.${chromosome}.gff3 > AGPv4_to_AGPv3_parseval.${chromosome}.output 2> AGPv4_to_AGPv3_parseval.${chromosome}.error &
```

Thank you.

**Comment by standage** [comment]
Hi again @sagnikbanerjee15, thank you for sending example files.

I reproduced the error you are reporting. The end of the log file reports a problem with the `Gene_Models_v3_to_v4.sorted.no.chr.6.gff3` data file.

```
mRNA '98938' (line 538) has directly adjacent exons
mRNA '98938' (line 538) has directly adjacent exons
error: mRNA 'GRMZM5G861268_T01' has 2 exons but 0 introns
```

It's unfortunate that this resulted in a segfault, not sure why it should have. But in any case it's clear that there is a problematic annotation in the file. The following `grep` command will pull out the features in question.

```
$ grep -e 'ID=98938;' -e 'Parent=98938;' Gene_Models_v3_to_v4.sorted.no.chr.6.gff3
6       MaizeGDB        exon    1849044 1849304 .       -       .       Name=GRMZM5G861268_E03;Parent=98938;ID=98940;version=1;assembly_name=AGPv3;ensembl_phase=-1;ensembl_end_phase=0;constitutive=0;rank=2
6       MaizeGDB        CDS     1849044 1849304 .       -       .       Parent=98938;ID=98939;assembly_name=AGPv3
6       MaizeGDB        mRNA    1849044 1850408 .       -       .       Name=GRMZM5G861268_T01;Parent=98936;ID=98938;logic_name=genebuilder;version=1;assembly_name=AGPv3;description=protein;biotype=protein_coding
6       MaizeGDB        exon    1849305 1850408 .       -       .       Name=GRMZM5G861268_E02;Parent=98938;ID=98942;version=1;assembly_name=AGPv3;ensembl_phase=0;ensembl_end_phase=0;constitutive=0;rank=1
6       MaizeGDB        CDS     1849305 1850408 .       -       .       Parent=98938;ID=98941;assembly_name=AGPv3
```

Examining these entries confirms the error message reported by ParsEval: that the transcript in question has two directly adjacent exons without any nucleotides in between, which doesn't make sense biologically.

**Comment by standage** [comment]
It looks like the problem you experienced with chr8 (#193) is due to the same issue. This is what was reported at the end of the log file.

```
mRNA '156411' (line 652) has directly adjacent exons
mRNA '156411' (line 652) has directly adjacent exons
error: mRNA 'GRMZM2G378906_T01' has 5 exons but 0 introns
warning: found no valid mRNAs for gene 'GRMZM2G378906'
mRNA '162915' (line 8105) has directly adjacent exons
mRNA '162915' (line 8105) has directly adjacent exons
error: mRNA 'GRMZM2G083328_T02' has 3 exons but 0 introns
```

**Comment by sagnikbanerjee15** [comment]
Thank you Daniel !!
