### ISSUE TITLE
Parseval multi-core & exhausted memory 

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BrendelGroup/AEGeAn#191]
Hello,

I tried to run parseval using multiple-cores but I could not find an option to request that. Also my run of parseval ran out of memory. I was running the program on a machine with 750G. Would you recommend running parseval for each chromosome?

Thanks.

**Comment by standage** [comment]
Hi again @sagnikbanerjee15.

There is no multicore or multithreaded mode for ParsEval.

As far as the memory usage, I'm surprised the program consumed so much memory. Splitting the input by chromosome is not typically required. There might be a memory leak somewhere in the program, but more likely I'd guess it has something to do with the input data. If you can post the input GFF3s I would be happy to take a quick look.

**Comment by standage** [comment]
Please feel free to re-open this thread if you can provide an example data set that triggers your problem.
