### ISSUE TITLE
Parseval Bug

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BrendelGroup/AEGeAn#193]
Hello,

I ran into a issue which gave the following error:
Assertion failed: (strlen(refr_vector) == gt_genome_node_get_length(pair->refr_clique) && strlen(pred_vector) == gt_genome_node_get_length(pair->refr_clique)), function clique_pair_comparative_analysis, file src/core/AgnCliquePair.c, line 340.
This is a bug, please report it at https://github.com/standage/AEGeAn/issues.

I was running the command
chromosome=8
nohup parseval -w -x AGPv4 -y AGPv3 -f html -o AGPv4_to_AGPv3_parseval.${chromosome} Zea_mays.AGPv4.39.tidy.${chromosome}.gff3 Gene_Models_v3_to_v4.sorted.no.chr.${chromosome}.gff3 > AGPv4_to_AGPv3_parseval.${chromosome}.output 2> AGPv4_to_AGPv3_parseval.${chromosome}.error &

[ref_and_pred_chr8.zip](https://github.com/BrendelGroup/AEGeAn/files/2207016/ref_and_pred_chr8.zip)

Thank you.

**Comment by standage** [comment]
Closing this thread. Please post updates to a thread on the original thread instead of opening a new issue. Thanks!
