### ISSUE TITLE
Problem running ParsEval: malloc: Incorrect checksum for freed object 0x7fcf8249ea98: probably modified after being freed.

### ISSUE THREAD

**Issue by vidyavuruputoor** [BrendelGroup/AEGeAn#197]
Hey,
I'm quite new to programming, and I'm trying to run ParsEval on my Mac.

I keep running into malloc_error_break errors or segmentation fault errors.

After scouring a while, I realised that the segmentation error is because of memory issues, but I have enough memory space to run the program.
I have no idea what the malloc_error_break is.

**Comment by vidyavuruputoor** [comment]
The input command I used was 

parseval -o output_1 -f html /Users/Vidya/Documents/augustus.hints.gff3 /Users/Vidya/Documents/run5.all_maker.gff
I was trying to compare MAKER and BRAKER annotations. 

I agree, I have split the files into smaller files with lesser number of contigs per file- but as I ran this command,

parseval -o output_1 -f html /Users/Vidya/Documents/augustus.hints.gff3 run5.all_maker_HS0004-1198.gff 

I got the following error:

Assertion failed: (ht), function gt_hashtable_get, file src/core/hashtable.c, line 285.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.

**Comment by vidyavuruputoor** [comment]
gt (GenomeTools) 1.5.10
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -m64 -Werror

This is my gt -version

**Comment by standage** [comment]
I'm closing this thread for now. Feel free to re-open it if you can provide an example data set to trigger the reported error.
