### ISSUE TITLE
error when making AEGeAn

### ISSUE THREAD

**Issue by xihuozi** [BrendelGroup/AEGeAn#198]
when I was making AEGeAn : 
[root@localhost AEGeAn-0.16.0]# make
[print inc/core/AgnVersion.h]
[compile AgnAttributeFilterStream]
src/core/AgnAttributeFilterStream.c:12:42: fatal error: extended/array_in_stream_api.h: no such file or directory
 #include "extended/array_in_stream_api.h"
                                          ^
compilation terminated.
make: *** [Makefile:102: obj/AgnAttributeFilterStream.o] Error 1
Is there anyone who knows how to solve this error?

**Comment by standage** [comment]
Hi @xihuozi, it appears that the compiler cannot find the GenomeTools library header files. There are two likely possibilities: 1) GenomeTools is not installed, or 2) it is installed in a non-standard location. In any case, this is discussed in detail in the [AEGeAn installation instructions](https://aegean.readthedocs.io/en/stable/install.html). If you still have issues after following these instructions, I'd be happy to help troubleshoot.

**Comment by xihuozi** [comment]
Hi ! 
This works for me :) 
Thanks for your help! Have a nice day.

**Comment by standage** [comment]
I'm glad it worked. Cheers!
