### ISSUE TITLE
fidibus-compact.py miscalculating sigma

### ISSUE THREAD

**Issue by timlai4** [BrendelGroup/AEGeAn#215]
[fidibus-compact.py](https://github.com/BrendelGroup/AEGeAn/blob/master/fidibus/scripts/fidibus-compact.py) can output a computed sigma to be larger than 1. 

I believe this is related to "length" (variable in script) being subtracted from iqnt and gqnt parameters, but milocus_occ does not account for gqnt. 
This conjecture is supported by running the same script that produced the larger than 1 sigma without the gqnt flag and the resulting output is sigma equal to exactly 1.0.

**Comment by vpbrendel** [comment]
I believe this issue has now been addressed.
