### ISSUE TITLE
How to infer CDS and UTR?

### ISSUE THREAD

**Issue by yhcccc** [BrendelGroup/AEGeAn#217]
![image](https://user-images.githubusercontent.com/35584554/69546075-fddc3180-0fcd-11ea-8d4d-7808c3966962.png)
Only exon and start & stop codon features like the .png declared, I want UTRs and CDS to be inferred.

After running `canon-gff3 < /Users/ccyh/Downloads/HUST_NotMatch.gff3 > out.gff3`, I got this:
![image](https://user-images.githubusercontent.com/35584554/69546568-f5d0c180-0fce-11ea-9d59-2bc9d2d45ada.png)

So I want to know how to complete the steps described in the introduction.
![image](https://user-images.githubusercontent.com/35584554/69546478-cfab2180-0fce-11ea-9a72-8dae3fb24fba.png)

**Comment by standage** [comment]
Greetings!

> Only exon and start & stop codon features like the .png declared, I want UTRs and CDS to be inferred.

I see `exon` and `mRNA` features declared in the first PNG (input), but no start and stop codons. The `##sequence-region` directives are added to the output even if they're not defined in the input (there should be 1 directive for each scaffold). The gene models would be below that. But without explicitly declared start/stop codons I'm not sure `canon-gff3` will create the correct output.

-----

Also, you attached 3 screenshots of text to this thread. Please consider using copy and paste to attach text to this thread in the future. You can wrap text blocks with ``` to have Github render it as code—see [Markdown](https://guides.github.com/features/mastering-markdown/) for more details.

**Comment by yhcccc** [comment]
> Greetings!
> 
> > Only exon and start & stop codon features like the .png declared, I want UTRs and CDS to be inferred.
> 
> I see `exon` and `mRNA` features declared in the first PNG (input), but no start and stop codons. The `##sequence-region` directives are added to the output even if they're not defined in the input (there should be 1 directive for each scaffold). The gene models would be below that. But without explicitly declared start/stop codons I'm not sure `canon-gff3` will create the correct output.

Thanks a lot for your response.
I will learn how to find the start/stop codons.
By the way, I will use Markdown to attach code. LOL

**Comment by standage** [comment]
Feel free to reopen this thread if you have any additional questions.
