### ISSUE TITLE
Changes to fidibus CLI and better support for local genome configs

### ISSUE THREAD

**Issue by standage** [BrendelGroup/AEGeAn#243]
Per #242, changes for the following are pending.

- [x] checksum validation support for locally stored files
- [x] updates to CLI documentation to clarify scope of `--cfgdir` argument
- [x] update terminology used in CLI documentation
    - currently we have:
        - "reference" genomes distributed with LocusPocus
        - "custom" "reference" genomes created by users, possibly stored in a custom config directory
        - "local" genomes, that require the specification of `--local, --label, --gdna, --gff3,` and `--prot` parameters
    - perhaps it's better to use:
        - local vs remote
        - "reference" vs "custom"

Any thoughts?

**Comment by vpbrendel** [comment]
I think reference for us really means getting downloaded from the NCBI RefSeq ftp site, doesn't?
Then we have a few "custom" functions (e.g. TAIR). And "local", which means we are not doing any download as this stage but point to a directory location on our local disk.

**Comment by standage** [comment]
Originally, "reference" was used to refer to any genome configuration distributed with the software to be downloaded from primary sources: these are mostly from RefSeq but also include BeeBase, the CRG folks in Spain, HymenopteraBase, and TAIR. When one invokes `fidibus --refr=Amel,Amh3,Am32,Am10` it refers to 4 different genome configurations from three different sources, only one of which is RefSeq. If we want "reference" to refer only to RefSeq, we'll need to reflect that in the CLI.

Also, the use of "custom" previously was a bit ambiguous: it could refer to "custom" reference genomes created by users (i.e., exists in RefSeq but not pre-configured with LocusPocus), but it was also used synonymously with "local" to refer to gdna/gff3/prot files stored on the same machine.

Practically, I don't anticipate users needing to create additional genome configs for sources other than RefSeq or GenBank. So I'm on board if we want to use "custom" to refer to primary sources other than RefSeq. In that case we could use "user-supplied" to distinguish configs created by users from configs shipped with the code, and "local" for files already present on disk.

**Comment by vpbrendel** [comment]
You are right. I think our documentation should reflect the code. --refr refers to something that involves download, I think; it does not matter whether the yml file is in the package genome_configs directory or in a new directory identified with the -c flag. If the download is not done by fidibus, then we use the --local flag. Maybe "refr" is not the best abbreviation. I got used to it, though. So could users.

**Comment by standage** [comment]
That's a good point, we don't need to be pedantic. I'll make sure the documentation is clear, but I won't stress about perfect conceptual purity.

**Comment by standage** [comment]
As it turns out, the changes merged in #242 already make it possible to validate checksums on local files without the need to awkwardly specify the location of the files in the .yml file AND invoke the `--gdna/--gff3/--prot` flags. The trick is to drop the `--local` flag. As long as `source: local` is set in the .yml file, then it will read the gdna/gff3/prot files from the .yml file correctly and validate the corresponding checksums. The `--local` flag should only be needed when the user is NOT providing a .yml file, in which case `--relax` will need to be used. Maybe we should auto-detect this last scenario for better support.

In which case, my proposed update should be a pretty minor cosmetic update to the CLI documentation.

**Comment by vpbrendel** [comment]
Correct:  fidibus -c genome_configs --refr=Dpul download prep
works.
