### ISSUE TITLE
Error 127 during install: [compile unit tests] [create libaegean] ar: creating libaegean.a bin/unittests: error while loading shared libraries: libgenometools.so: cannot open shared object file: No such file or directory make: *** [agn-test] Error 127

### ISSUE THREAD

**Issue by MatthewOtt** [BrendelGroup/AEGeAn#260]
I was nearly finished with the install, when I received the following error message:

(base) ottxx142@ln1002 [~/local/AEGeAn-0.16.0] % make prefix=~/local test
[print inc/core/AgnVersion.h]
[compile AgnAttributeFilterStream]
[compile AgnCliquePair]
[compile AgnCompareReportHTML]
[compile AgnCompareReportText]
[compile AgnComparison]
[compile AgnFilterStream]
[compile AgnGaevalVisitor]
[compile AgnGeneStream]
[compile AgnInferCDSVisitor]
[compile AgnInferExonsVisitor]
[compile AgnInferParentStream]
[compile AgnLocus]
[compile AgnLocusFilterStream]
[compile AgnLocusMapVisitor]
[compile AgnLocusRefineStream]
[compile AgnLocusStream]
[compile AgnMrnaRepVisitor]
[compile AgnPseudogeneFixVisitor]
[compile AgnRemoveChildrenVisitor]
[compile AgnTranscriptClique]
[compile AgnTypecheck]
[compile AgnUnitTest]
[compile AgnUtils]
[compile ParsEval]
[compile CanonGFF3]
[compile LocusPocus]
[compile GAEVAL]
[compile Xtractore]
[compile bin/pmrna]
[compile bin/tidygff3]
[compile unit tests]
[create libaegean]
ar: creating libaegean.a
bin/unittests: error while loading shared libraries: libgenometools.so: cannot open shared object file: No such file or directory
make: *** [agn-test] Error 127

**Comment by vpbrendel** [comment]
see installation notes, file https://github.com/BrendelGroup/AEGeAn/blob/master/Singularity

which shows how to install genometools
