### ISSUE TITLE
Build failure due to missing sources

### ISSUE THREAD

**Issue by martin-g** [BrendelGroup/AEGeAn#261]
Hello,

I am trying to build AEGeAn locally but it fails with:
```
$ make
[print inc/core/AgnVersion.h]
[compile AgnAttributeFilterStream]
src/core/AgnAttributeFilterStream.c:12:10: fatal error: extended/array_in_stream_api.h: No such file or directory
   12 | #include "extended/array_in_stream_api.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:115: obj/AgnAttributeFilterStream.o] Error 1
```

and indeed there is no `extended` folder at https://github.com/BrendelGroup/AEGeAn/tree/master/src/core

**Comment by martin-g** [comment]
I also tried to follow the steps at https://github.com/BrendelGroup/AEGeAn/blob/master/INSTALL.md but it fails at:
```
$ singularity pull --name aegean.simg shub://BrendelGroup/AEGeAn
INFO:    Downloading shub image
FATAL:   While pulling shub image: error fetching image to cache: download did not succeed: 403 Forbidden
```

**Comment by vpbrendel** [comment]
wget https://brendelgroup.org/SingularityHub/aegean.sif

should work.

**Comment by martin-g** [comment]
Thank you, @vpbrendel !
Downloading it via `wget` works!
I can successfully execute:
```
$ singularity exec -e -B $(pwd) aegean.sif fidibus -h
usage: fidibus [-h] [-v] [-d DLT] [-w WD] [-p P] [--refr LBL | --refrbatch LBL] [-c DIR] [--local] [--label LBL] [--gdna GDNA] [--gff3 GFF3] [--prot PROT] [-x] [-f PFX] [--keep PTN [PTN ...]] [--fullclean]
               [--cdargs ARGS]
               task [task ...]
```

but this does not really help me building from sources. Or I don't understand what to do next.

**Comment by splaisan** [comment]
Thanks @vpbrendel,
I had the same issue and your direct link worked.
Maybe good to correct the INSTALL.md page so that others find the image.
thanks

**Comment by estolle** [comment]
+1
I encountered the exact same problem (install from source fails, singularity pull fails)

**Comment by vpbrendel** [comment]
Build from source should work with the latest genometools version (1.6.5).
Volker
