### ISSUE TITLE
Assertion failed line 340

### ISSUE THREAD

**Issue by Zhuxitong** [BrendelGroup/AEGeAn#270]
Hello developers:

I want to compare old annotation with update ones. I just reformat my two gff3 file to ensure that they follow the criterion of GFF3 by comparing my gff3 to the one in data/gff3 amel-aug-athal-param.gff3. But I still met the following bug after it run a while:

> Assertion failed: (strlen(refr_vector) == gt_genome_node_get_length(pair->refr_clique) && strlen(pred_vector) == gt_genome_node_get_length(pair->refr_clique)), function clique_pair_comparative_analysis, file src/core/AgnCliquePair.c, line 340.

My command is like:
`parseval -w -d -o parseval.out Omh63.can.gff3 newOmh63.can.gff3`

I provide my files as follows:
https://drive.google.com/file/d/1OqSRNm_6KS1X7UjqO4XvswXznxLFbaZT/view?usp=drive_link
https://drive.google.com/file/d/1JYlCnO7dBab-EYnpKdoKzZ3lPNYkhpuw/view?usp=drive_link

Thank you in advance. Parseval is very useful as there are many and many updated annotation files!

**Comment by Zhuxitong** [comment]
I have solved this problem. The main reaseon for this bug is that some of my transcripts have wrong coordinates. Specifically, the range of sub-features such as CDS or 5'UTR may exceed the defiend range of its parental gene or transcripts. 

I manually corrected those errors and the bug fixed. Hope it will be helpful for others who want to use this tool.

**Comment by standage** [comment]
I'm glad you were able to resolve the issue. Thank you for the follow-up!
